//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediComponents {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediComponents.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicts the degree of shunting in the lungs by comparing the partial pressure of O2 in the alveoli to the partial pressure of O2 in the arterial blood. The difference between the two partial pressures indicates how well the oxygen is moving form the alveoli into the blood..
        /// </summary>
        public static string AaGradientExplanation {
            get {
                return ResourceManager.GetString("AaGradientExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-a Gradient = {0} mmHg.
        /// </summary>
        public static string AaGradientResultFormat {
            get {
                return ResourceManager.GetString("AaGradientResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-a Gradient.
        /// </summary>
        public static string AaGradientTitle {
            get {
                return ResourceManager.GetString("AaGradientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 60.
        /// </summary>
        public static string ABCD2Age0 {
            get {
                return ResourceManager.GetString("ABCD2Age0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 or older.
        /// </summary>
        public static string ABCD2Age1 {
            get {
                return ResourceManager.GetString("ABCD2Age1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string ABCD2BP0 {
            get {
                return ResourceManager.GetString("ABCD2BP0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevated (140/90 or higher).
        /// </summary>
        public static string ABCD2BP1 {
            get {
                return ResourceManager.GetString("ABCD2BP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other than those specified.
        /// </summary>
        public static string ABCD2CF0 {
            get {
                return ResourceManager.GetString("ABCD2CF0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech disturbance, no weakness.
        /// </summary>
        public static string ABCD2CF1 {
            get {
                return ResourceManager.GetString("ABCD2CF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unilateral (one sided) weakness.
        /// </summary>
        public static string ABCD2CF2 {
            get {
                return ResourceManager.GetString("ABCD2CF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No diabetes.
        /// </summary>
        public static string ABCD2Di0 {
            get {
                return ResourceManager.GetString("ABCD2Di0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetes present.
        /// </summary>
        public static string ABCD2Di1 {
            get {
                return ResourceManager.GetString("ABCD2Di1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 10 minutes.
        /// </summary>
        public static string ABCD2Du0 {
            get {
                return ResourceManager.GetString("ABCD2Du0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10-59 minutes.
        /// </summary>
        public static string ABCD2Du1 {
            get {
                return ResourceManager.GetString("ABCD2Du1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 minutes or longer.
        /// </summary>
        public static string ABCD2Du2 {
            get {
                return ResourceManager.GetString("ABCD2Du2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a patient experiences a Transient Ischemic Attack (TIA) the ABCD2 score is used to determine the risk for stroke within the first two days post attack. The ABCD2 score is graded on 5 criteria: clinical features, age, duration of TIA, blood pressure, and presence of diabetes. The evaluation is added up and the score ranges from 0‐7: 0‐3 is low (2 day risk = 1.0%, 7 day risk = 1.2), 4‐5 is moderate (2 day risk = 4.1%, 7 day risk = 5.9%), 6‐7 is high (2 day risk = 8.1%, 7 day risk = 11.7%)..
        /// </summary>
        public static string ABCD2Explanation {
            get {
                return ResourceManager.GetString("ABCD2Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (high).
        /// </summary>
        public static string ABCD2High {
            get {
                return ResourceManager.GetString("ABCD2High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (low).
        /// </summary>
        public static string ABCD2Low {
            get {
                return ResourceManager.GetString("ABCD2Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (moderate).
        /// </summary>
        public static string ABCD2Mod {
            get {
                return ResourceManager.GetString("ABCD2Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        public static string ABCD2ResultFormat {
            get {
                return ResourceManager.GetString("ABCD2ResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCD2.
        /// </summary>
        public static string ABCD2Title {
            get {
                return ResourceManager.GetString("ABCD2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid Base Compensation.
        /// </summary>
        public static string ABCompTitle {
            get {
                return ResourceManager.GetString("ABCompTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        public static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to African American.
        /// </summary>
        public static string AfricanAmerican {
            get {
                return ResourceManager.GetString("AfricanAmerican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculated estimated difference between the measured anions and cations in serum.  Common cations include Na, K, Ca and Mg.  Common anions are Cl, Bicarb, and phosphate.  Anion gap is used to help identify cause of metabolic acidosis.  Increased anion gap acidosis indicates MUDPILERS etiology, while non-anion gap acidosis indicates HARDUPS etiology.  Normal anion gap is generally regarded as &lt;11 mEq/L.  A low anion gap is commonly brought about by hypoalbuminemia.
        ///
        ///Anion Gap Metabolic Acidosis: MUDPIL [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AnionGapExplanation {
            get {
                return ResourceManager.GetString("AnionGapExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anion Gap.
        /// </summary>
        public static string AnionGapTitle {
            get {
                return ResourceManager.GetString("AnionGapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string ApgarActivity {
            get {
                return ResourceManager.GetString("ApgarActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ApgarActivity0 {
            get {
                return ResourceManager.GetString("ApgarActivity0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some flexion.
        /// </summary>
        public static string ApgarActivity1 {
            get {
                return ResourceManager.GetString("ApgarActivity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexed arms and legs, resist extension.
        /// </summary>
        public static string ApgarActivity2 {
            get {
                return ResourceManager.GetString("ApgarActivity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string ApgarAppearance {
            get {
                return ResourceManager.GetString("ApgarAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue or pale all over.
        /// </summary>
        public static string ApgarAppearance0 {
            get {
                return ResourceManager.GetString("ApgarAppearance0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue at extremities, body pink.
        /// </summary>
        public static string ApgarAppearance1 {
            get {
                return ResourceManager.GetString("ApgarAppearance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body and extremities pink.
        /// </summary>
        public static string ApgarAppearance2 {
            get {
                return ResourceManager.GetString("ApgarAppearance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to grade newborn babies on 5 criteria on a scale of 0‐2. Performed at one and five minutes after birth. If the score is low, it may be repeated at 10, 15 and 30 minutes as well. Scores are summed and the total score is evaluated. 3 and below is considered critically low, 4‐6 is low, 7‐10 is normal..
        /// </summary>
        public static string ApgarExplanation {
            get {
                return ResourceManager.GetString("ApgarExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grimace.
        /// </summary>
        public static string ApgarGrimace {
            get {
                return ResourceManager.GetString("ApgarGrimace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response to stimulation.
        /// </summary>
        public static string ApgarGrimace0 {
            get {
                return ResourceManager.GetString("ApgarGrimace0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grimace/feeble cry when stimulated.
        /// </summary>
        public static string ApgarGrimace1 {
            get {
                return ResourceManager.GetString("ApgarGrimace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cry or pull away when stimluated.
        /// </summary>
        public static string ApgarGrimace2 {
            get {
                return ResourceManager.GetString("ApgarGrimace2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse.
        /// </summary>
        public static string ApgarPulse {
            get {
                return ResourceManager.GetString("ApgarPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        public static string ApgarPulse0 {
            get {
                return ResourceManager.GetString("ApgarPulse0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below 100.
        /// </summary>
        public static string ApgarPulse1 {
            get {
                return ResourceManager.GetString("ApgarPulse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 or above.
        /// </summary>
        public static string ApgarPulse2 {
            get {
                return ResourceManager.GetString("ApgarPulse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiration.
        /// </summary>
        public static string ApgarRespiration {
            get {
                return ResourceManager.GetString("ApgarRespiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        public static string ApgarRespiration0 {
            get {
                return ResourceManager.GetString("ApgarRespiration0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak, irregular, gasping.
        /// </summary>
        public static string ApgarRespiration1 {
            get {
                return ResourceManager.GetString("ApgarRespiration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong, lusty cry.
        /// </summary>
        public static string ApgarRespiration2 {
            get {
                return ResourceManager.GetString("ApgarRespiration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APGAR.
        /// </summary>
        public static string ApgarTitle {
            get {
                return ResourceManager.GetString("ApgarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediCalc.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Pressure.
        /// </summary>
        public static string BloodPressure {
            get {
                return ResourceManager.GetString("BloodPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for adults over 20 years old, used to indicate weight status and correlates with body fat. May overestimate BMI in athletes and those
        ///with muscular build. May underestimate in the elderly and in those who have lost muscle mass..
        /// </summary>
        public static string BmiExplanation {
            get {
                return ResourceManager.GetString("BmiExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (in inches).
        /// </summary>
        public static string BmiHeight {
            get {
                return ResourceManager.GetString("BmiHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (normal).
        /// </summary>
        public static string BmiNormal {
            get {
                return ResourceManager.GetString("BmiNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (obese).
        /// </summary>
        public static string BmiObese {
            get {
                return ResourceManager.GetString("BmiObese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (overweight).
        /// </summary>
        public static string BmiOverweight {
            get {
                return ResourceManager.GetString("BmiOverweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI.
        /// </summary>
        public static string BmiTitle {
            get {
                return ResourceManager.GetString("BmiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (underweight).
        /// </summary>
        public static string BmiUnderweight {
            get {
                return ResourceManager.GetString("BmiUnderweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (in pounds).
        /// </summary>
        public static string BmiWeight {
            get {
                return ResourceManager.GetString("BmiWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation is used when the patient albumin levels are abnormal.  Used to make up for the change in total calcium due to altered albumin binding.  The calculation gives an estimate of what the calcium level would be if the albumin levels were normal.  When the patient has decreased albumin, the corrected calcium level will be higher than the total calcium.
        ///
        ///Normal Ca levels = 8.5 - 10.5 mg/dL.
        /// </summary>
        public static string CACorrectionExplanation {
            get {
                return ResourceManager.GetString("CACorrectionExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcium/albumin Correction.
        /// </summary>
        public static string CACorrectionTitle {
            get {
                return ResourceManager.GetString("CACorrectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to estimate creatinine clearance which is used to estimate GFR in ml/min.  Glomerular filtration rate (GFR) is the volume of fluid filtered from the glomerular capillaries into the bowman&apos;s capsule typically given at a per minute rate..
        /// </summary>
        public static string CGEExplanation {
            get {
                return ResourceManager.GetString("CGEExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cockcroft-Gault Equation.
        /// </summary>
        public static string CGETitle {
            get {
                return ResourceManager.GetString("CGETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical Features.
        /// </summary>
        public static string ClinicalFeatures {
            get {
                return ResourceManager.GetString("ClinicalFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FiO₂.
        /// </summary>
        public static string CompoundFiO2 {
            get {
                return ResourceManager.GetString("CompoundFiO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCO₃.
        /// </summary>
        public static string CompoundHCO3 {
            get {
                return ResourceManager.GetString("CompoundHCO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaCO₂.
        /// </summary>
        public static string CompoundPaCO2 {
            get {
                return ResourceManager.GetString("CompoundPaCO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaO₂.
        /// </summary>
        public static string CompoundPaO2 {
            get {
                return ResourceManager.GetString("CompoundPaO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pCO₂.
        /// </summary>
        public static string CompoundpCO2 {
            get {
                return ResourceManager.GetString("CompoundpCO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pH.
        /// </summary>
        public static string CompoundpH {
            get {
                return ResourceManager.GetString("CompoundpH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatinine.
        /// </summary>
        public static string Creatinine {
            get {
                return ResourceManager.GetString("Creatinine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to correlate changing from one corticosteroid to another based on anti-inflammatory potencies.  The table below shows the values used to calculate doses.  Biological half life is used to more accurately reflect the duration of action in vivo of the corticosteroid.  Fludrocortisone is typically used for it&apos;s mineralcorticoid action and has negligible anti-inflammatory effects at therapeutic doses.
        ///  - Short bio-half life = 8-12 hours
        ///  - Intermediate bio-half life = 12-36 hours
        ///  - Long bio-half life [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CSCExplanation {
            get {
                return ResourceManager.GetString("CSCExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corticosteroid Converter.
        /// </summary>
        public static string CSCTitle {
            get {
                return ResourceManager.GetString("CSCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetes.
        /// </summary>
        public static string Diabetes {
            get {
                return ResourceManager.GetString("Diabetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected.
        /// </summary>
        public static string Expected {
            get {
                return ResourceManager.GetString("Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        public static string ExplanationTabTitle {
            get {
                return ResourceManager.GetString("ExplanationTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        public static string FormulaTabTitle {
            get {
                return ResourceManager.GetString("FormulaTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string FormulaTitleFormatString {
            get {
                return ResourceManager.GetString("FormulaTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the Modification of Diet in Renal Diseas study, is used to estimate glomerular filtration rate or the flow rate of filtered fluid through the kidney.  Will underestimate GFR in patients with GFR &gt;60 mL/min..
        /// </summary>
        public static string GfrExplanation {
            get {
                return ResourceManager.GetString("GfrExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFR (MRDR).
        /// </summary>
        public static string GfrTitle {
            get {
                return ResourceManager.GetString("GfrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicative of {0}.
        /// </summary>
        public static string IndicativeOfFormat {
            get {
                return ResourceManager.GetString("IndicativeOfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metabolic Acidosis.
        /// </summary>
        public static string MetaAcid {
            get {
                return ResourceManager.GetString("MetaAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metabolic Alkalosis.
        /// </summary>
        public static string MetaAlka {
            get {
                return ResourceManager.GetString("MetaAlka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiratory Acidosis.
        /// </summary>
        public static string RespAcid {
            get {
                return ResourceManager.GetString("RespAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiratory Alkalosis.
        /// </summary>
        public static string RespAlka {
            get {
                return ResourceManager.GetString("RespAlka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score = .
        /// </summary>
        public static string ScoreEquals {
            get {
                return ResourceManager.GetString("ScoreEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual level is {0} (potential underlying {1}).
        /// </summary>
        public static string UnderlyingFormat {
            get {
                return ResourceManager.GetString("UnderlyingFormat", resourceCulture);
            }
        }
    }
}
