//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediComponents {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediComponents.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicts the degree of shunting in the lungs by comparing the partial pressure of O2 in the alveoli to the partial pressure of O2 in the arterial blood. The difference between the two partial pressures indicates how well the oxygen is moving form the alveoli into the blood..
        /// </summary>
        internal static string AaGradientExplanation {
            get {
                return ResourceManager.GetString("AaGradientExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-a Gradient.
        /// </summary>
        internal static string AaGradientTitle {
            get {
                return ResourceManager.GetString("AaGradientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 60.
        /// </summary>
        internal static string ABCD2Age0 {
            get {
                return ResourceManager.GetString("ABCD2Age0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 or older.
        /// </summary>
        internal static string ABCD2Age1 {
            get {
                return ResourceManager.GetString("ABCD2Age1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string ABCD2BP0 {
            get {
                return ResourceManager.GetString("ABCD2BP0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevated (140/90 or higher).
        /// </summary>
        internal static string ABCD2BP1 {
            get {
                return ResourceManager.GetString("ABCD2BP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other than those specified.
        /// </summary>
        internal static string ABCD2CF0 {
            get {
                return ResourceManager.GetString("ABCD2CF0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech disturbance, no weakness.
        /// </summary>
        internal static string ABCD2CF1 {
            get {
                return ResourceManager.GetString("ABCD2CF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unilateral (one sided) weakness.
        /// </summary>
        internal static string ABCD2CF2 {
            get {
                return ResourceManager.GetString("ABCD2CF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No diabetes.
        /// </summary>
        internal static string ABCD2Di0 {
            get {
                return ResourceManager.GetString("ABCD2Di0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetes present.
        /// </summary>
        internal static string ABCD2Di1 {
            get {
                return ResourceManager.GetString("ABCD2Di1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 10 minutes.
        /// </summary>
        internal static string ABCD2Du0 {
            get {
                return ResourceManager.GetString("ABCD2Du0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10-59 minutes.
        /// </summary>
        internal static string ABCD2Du1 {
            get {
                return ResourceManager.GetString("ABCD2Du1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 minutes or longer.
        /// </summary>
        internal static string ABCD2Du2 {
            get {
                return ResourceManager.GetString("ABCD2Du2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a patient experiences a Transient Ischemic Attack (TIA) the ABCD2 score is used to determine the risk for stroke within the first two days post attack. The ABCD2 score is graded on 5 criteria: clinical features, age, duration of TIA, blood pressure, and presence of diabetes. The evaluation is added up and the score ranges from 0‐7: 0‐3 is low (2 day risk = 1.0%, 7 day risk = 1.2), 4‐5 is moderate (2 day risk = 4.1%, 7 day risk = 5.9%), 6‐7 is high (2 day risk = 8.1%, 7 day risk = 11.7%)..
        /// </summary>
        internal static string ABCD2Explanation {
            get {
                return ResourceManager.GetString("ABCD2Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (high).
        /// </summary>
        internal static string ABCD2High {
            get {
                return ResourceManager.GetString("ABCD2High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (low).
        /// </summary>
        internal static string ABCD2Low {
            get {
                return ResourceManager.GetString("ABCD2Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (moderate).
        /// </summary>
        internal static string ABCD2Mod {
            get {
                return ResourceManager.GetString("ABCD2Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCD2.
        /// </summary>
        internal static string ABCD2Title {
            get {
                return ResourceManager.GetString("ABCD2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid Base Compensation.
        /// </summary>
        internal static string ABCompTitle {
            get {
                return ResourceManager.GetString("ABCompTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        internal static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to African American.
        /// </summary>
        internal static string AfricanAmerican {
            get {
                return ResourceManager.GetString("AfricanAmerican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculated estimated difference between the measured anions and cations in serum.  Common cations include Na, K, Ca and Mg.  Common anions are Cl, Bicarb, and phosphate.  Anion gap is used to help identify cause of metabolic acidosis.  Increased anion gap acidosis indicates MUDPILERS etiology, while non-anion gap acidosis indicates HARDUPS etiology.  Normal anion gap is generally regarded as &lt;11 mEq/L.  A low anion gap is commonly brought about by hypoalbuminemia.
        ///
        ///Anion Gap Metabolic Acidosis: MUDPIL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnionGapExplanation {
            get {
                return ResourceManager.GetString("AnionGapExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anion Gap.
        /// </summary>
        internal static string AnionGapTitle {
            get {
                return ResourceManager.GetString("AnionGapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string ApgarActivity {
            get {
                return ResourceManager.GetString("ApgarActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ApgarActivity0 {
            get {
                return ResourceManager.GetString("ApgarActivity0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some flexion.
        /// </summary>
        internal static string ApgarActivity1 {
            get {
                return ResourceManager.GetString("ApgarActivity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexed arms and legs, resist extension.
        /// </summary>
        internal static string ApgarActivity2 {
            get {
                return ResourceManager.GetString("ApgarActivity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string ApgarAppearance {
            get {
                return ResourceManager.GetString("ApgarAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue or pale all over.
        /// </summary>
        internal static string ApgarAppearance0 {
            get {
                return ResourceManager.GetString("ApgarAppearance0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue at extremities, body pink.
        /// </summary>
        internal static string ApgarAppearance1 {
            get {
                return ResourceManager.GetString("ApgarAppearance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body and extremities pink.
        /// </summary>
        internal static string ApgarAppearance2 {
            get {
                return ResourceManager.GetString("ApgarAppearance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to grade newborn babies on 5 criteria on a scale of 0‐2. Performed at one and five minutes after birth. If the score is low, it may be repeated at 10, 15 and 30 minutes as well. Scores are summed and the total score is evaluated. 3 and below is considered critically low, 4‐6 is low, 7‐10 is normal..
        /// </summary>
        internal static string ApgarExplanation {
            get {
                return ResourceManager.GetString("ApgarExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grimace.
        /// </summary>
        internal static string ApgarGrimace {
            get {
                return ResourceManager.GetString("ApgarGrimace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response to stimulation.
        /// </summary>
        internal static string ApgarGrimace0 {
            get {
                return ResourceManager.GetString("ApgarGrimace0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grimace/feeble cry when stimulated.
        /// </summary>
        internal static string ApgarGrimace1 {
            get {
                return ResourceManager.GetString("ApgarGrimace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cry or pull away when stimluated.
        /// </summary>
        internal static string ApgarGrimace2 {
            get {
                return ResourceManager.GetString("ApgarGrimace2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse.
        /// </summary>
        internal static string ApgarPulse {
            get {
                return ResourceManager.GetString("ApgarPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        internal static string ApgarPulse0 {
            get {
                return ResourceManager.GetString("ApgarPulse0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below 100.
        /// </summary>
        internal static string ApgarPulse1 {
            get {
                return ResourceManager.GetString("ApgarPulse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 or above.
        /// </summary>
        internal static string ApgarPulse2 {
            get {
                return ResourceManager.GetString("ApgarPulse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiration.
        /// </summary>
        internal static string ApgarRespiration {
            get {
                return ResourceManager.GetString("ApgarRespiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        internal static string ApgarRespiration0 {
            get {
                return ResourceManager.GetString("ApgarRespiration0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak, irregular, gasping.
        /// </summary>
        internal static string ApgarRespiration1 {
            get {
                return ResourceManager.GetString("ApgarRespiration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong, lusty cry.
        /// </summary>
        internal static string ApgarRespiration2 {
            get {
                return ResourceManager.GetString("ApgarRespiration2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APGAR.
        /// </summary>
        internal static string ApgarTitle {
            get {
                return ResourceManager.GetString("ApgarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediCalc.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Pressure.
        /// </summary>
        internal static string BloodPressure {
            get {
                return ResourceManager.GetString("BloodPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for adults over 20 years old, used to indicate weight status and correlates with body fat. May overestimate BMI in athletes and those
        ///with muscular build. May underestimate in the elderly and in those who have lost muscle mass..
        /// </summary>
        internal static string BmiExplanation {
            get {
                return ResourceManager.GetString("BmiExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (in inches).
        /// </summary>
        internal static string BmiHeight {
            get {
                return ResourceManager.GetString("BmiHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (normal).
        /// </summary>
        internal static string BmiNormal {
            get {
                return ResourceManager.GetString("BmiNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (obese).
        /// </summary>
        internal static string BmiObese {
            get {
                return ResourceManager.GetString("BmiObese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (overweight).
        /// </summary>
        internal static string BmiOverweight {
            get {
                return ResourceManager.GetString("BmiOverweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI.
        /// </summary>
        internal static string BmiTitle {
            get {
                return ResourceManager.GetString("BmiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (underweight).
        /// </summary>
        internal static string BmiUnderweight {
            get {
                return ResourceManager.GetString("BmiUnderweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (in pounds).
        /// </summary>
        internal static string BmiWeight {
            get {
                return ResourceManager.GetString("BmiWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation is used when the patient albumin levels are abnormal.  Used to make up for the change in total calcium due to altered albumin binding.  The calculation gives an estimate of what the calcium level would be if the albumin levels were normal.  When the patient has decreased albumin, the corrected calcium level will be higher than the total calcium.
        ///
        ///Normal Ca levels = 8.5 - 10.5 mg/dL.
        /// </summary>
        internal static string CACorrectionExplanation {
            get {
                return ResourceManager.GetString("CACorrectionExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcium/albumin Correction.
        /// </summary>
        internal static string CACorrectionTitle {
            get {
                return ResourceManager.GetString("CACorrectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to estimate creatinine clearance which is used to estimate GFR in ml/min.  Glomerular filtration rate (GFR) is the volume of fluid filtered from the glomerular capillaries into the bowman&apos;s capsule typically given at a per minute rate..
        /// </summary>
        internal static string CGEExplanation {
            get {
                return ResourceManager.GetString("CGEExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cockcroft-Gault Equation.
        /// </summary>
        internal static string CGETitle {
            get {
                return ResourceManager.GetString("CGETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical Features.
        /// </summary>
        internal static string ClinicalFeatures {
            get {
                return ResourceManager.GetString("ClinicalFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatinine.
        /// </summary>
        internal static string Creatinine {
            get {
                return ResourceManager.GetString("Creatinine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to correlate changing from one corticosteroid to another based on anti-inflammatory potencies.  The table below shows the values used to calculate doses.  Biological half life is used to more accurately reflect the duration of action in vivo of the corticosteroid.  Fludrocortisone is typically used for it&apos;s mineralcorticoid action and has negligible anti-inflammatory effects at therapeutic doses.
        ///  - Short bio-half life = 8-12 hours
        ///  - Intermediate bio-half life = 12-36 hours
        ///  - Long bio-half life [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSCExplanation {
            get {
                return ResourceManager.GetString("CSCExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corticosteroid Converter.
        /// </summary>
        internal static string CSCTitle {
            get {
                return ResourceManager.GetString("CSCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetes.
        /// </summary>
        internal static string Diabetes {
            get {
                return ResourceManager.GetString("Diabetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected.
        /// </summary>
        internal static string Expected {
            get {
                return ResourceManager.GetString("Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        internal static string ExplanationTabTitle {
            get {
                return ResourceManager.GetString("ExplanationTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        internal static string FormulaTabTitle {
            get {
                return ResourceManager.GetString("FormulaTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string FormulaTitleFormatString {
            get {
                return ResourceManager.GetString("FormulaTitleFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the Modification of Diet in Renal Diseas study, is used to estimate glomerular filtration rate or the flow rate of filtered fluid through the kidney.  Will underestimate GFR in patients with GFR &gt;60 mL/min..
        /// </summary>
        internal static string GfrExplanation {
            get {
                return ResourceManager.GetString("GfrExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFR (MRDR).
        /// </summary>
        internal static string GfrTitle {
            get {
                return ResourceManager.GetString("GfrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicative of {0}.
        /// </summary>
        internal static string IndicativeOfFormat {
            get {
                return ResourceManager.GetString("IndicativeOfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metabolic Acidosis.
        /// </summary>
        internal static string MetaAcid {
            get {
                return ResourceManager.GetString("MetaAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metabolic Alkalosis.
        /// </summary>
        internal static string MetaAlka {
            get {
                return ResourceManager.GetString("MetaAlka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiratory Acidosis.
        /// </summary>
        internal static string RespAcid {
            get {
                return ResourceManager.GetString("RespAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respiratory Alkalosis.
        /// </summary>
        internal static string RespAlka {
            get {
                return ResourceManager.GetString("RespAlka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score = .
        /// </summary>
        internal static string ScoreEquals {
            get {
                return ResourceManager.GetString("ScoreEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual level is {0} (potential underlying {1}).
        /// </summary>
        internal static string UnderlyingFormat {
            get {
                return ResourceManager.GetString("UnderlyingFormat", resourceCulture);
            }
        }
    }
}
